services:
  - type: web
    name: housing-price-prediction-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 5000
    pythonVersion: 3.9
    workingDirectory: backend
    start: gunicorn backend.app:app --bind 0.0.0.0:$PORT

